import OpenAI from 'openai';
import { TextNormalizer } from '@/lib/utils/TextNormalizer';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

export interface Intent {
  type: 'action' | 'question' | 'conversation';
  category: string; // create_task, advice_request, greeting, etc.
  confidence: number; // 0-1
  entities: {
    tasks?: string[];
    dates?: string[];
    projects?: string[];
    habits?: string[];
    numbers?: number[];
    [key: string]: any;
  };
  parameters: Record<string, any>;
  emotionalContext?: 'positive' | 'neutral' | 'negative' | 'stressed' | 'motivated';
  requiresAction: boolean;
  suggestedResponse?: string;
}

export class IntentDetectionService {
  /**
   * Analyser l'intention d'un message utilisateur
   */
  static async detectIntent(
    message: string,
    userContext?: any
  ): Promise<Intent> {
    // Normaliser le message avant traitement
    const normalizedMessage = TextNormalizer.normalize(message);
    const systemPrompt = `Tu es un expert en compréhension du langage naturel pour un assistant de productivité.

Ton rôle : analyser un message utilisateur et déterminer son intention, MÊME SI :
- Il y a des fautes d'orthographe (ex: "kommence", "travaiiler", "journee")
- Le langage est informel/SMS (ex: "c parti", "j'veux", "dem1n")
- La formulation est approximative ou incomplète
- Les accents manquent (ex: "journee" au lieu de "journée")
- Il y a des abréviations (ex: "planif", "rdv", "bcp")

**IMPORTANT : Sois TRÈS tolérant aux erreurs et variations. Si tu n'es pas sûr à 100%, choisis l'intention la plus probable.**

**Types d'INTENTIONS** :

1. ACTION (nécessite une exécution) :
   - create_task : Créer tâche(s)
   - list_tasks : Lister tâches
   - complete_task : Terminer tâche
   - plan_tomorrow : Planifier demain
   - start_deepwork : Démarrer session Deep Work
   - end_deepwork : Terminer session Deep Work
   - pause_deepwork : Mettre en pause session
   - resume_deepwork : Reprendre session
   - status_deepwork : Statut session
   - track_habit : Habitude
   - update_task : Modifier tâche
   - delete_task : Supprimer tâche

2. QUESTION (nécessite une réponse) :
   - advice_request : Conseil, demande d'aide générale
   - how_to : Tutoriel, processus étape par étape
   - status_check : Statut général
   - explanation : Explication d'un concept ou processus
   - statistics : Stats
   - recommendation : Suggestion
   - help_request : Demande d'aide spécifique (comment faire, processus, guidance)

3. CONVERSATION (échange social) :
   - greeting : Salutation
   - thanks : Remerciement
   - motivation : Besoin motivation
   - frustration : Frustration
   - small_talk : Discussion informelle

**EXEMPLES EXHAUSTIFS DE VARIATIONS** :

=== START_DEEPWORK ===
"je commence à travailler" / "je comence à travaiiler" (fautes)
"je démarre une session" / "je démarre une session" (normal)
"lance une session de travail" / "lance une session de travaiil" (faute)
"go deep work" / "go deep work" (normal)
"je veux travailler" / "j'veux travaiiler" (sms + faute)
"c'est parti pour travailler" / "c parti pour bosser" (sms)
"kommence le travail" / "commance à travailler" (fautes)
"je veux me concentrer" / "j'veux me concentrer" (sms)
"allez on y va" / "allez on commence" (normal)
"c'est parti" / "c parti" (sms)
"je peux commencer ?" / "je peux commencer ?" (normal)
"démarre une session de concentration" / "demarre une session de concentration" (faute)
"je vais bosser maintenant" / "j'vais bosser mnt" (sms)
"on commence le travail" / "on comence le travaiil" (fautes)
"lance-moi une session" / "lance moi une session" (normal)
"je me mets au boulot" / "j'me mets au boulot" (sms)
"c'est l'heure de travailler" / "c l'heure de travaiiler" (sms + faute)
"je démarre mon deep work" / "je demarre mon deep work" (faute)
"active une session" / "active une session" (normal)
"je me concentre maintenant" / "j'me concentre mnt" (sms)
"commençons à travailler" / "comencons à travaiiler" (fautes)
"démarre le mode focus" / "demarre le mode focus" (faute)
"je vais me concentrer" / "j'vais me concentrer" (sms)
"on y va pour le travail" / "on y va pour le travaiil" (faute)
"je lance une session" / "je lance une session" (normal)
"c'est parti je bosse" / "c parti j'bosse" (sms)
"je commence maintenant" / "je comence mnt" (sms + faute)
"démarre une session de travail intense" / "demarre une session de travaiil intense" (fautes)
"je me mets en mode concentration" / "j'me mets en mode concentration" (sms)
"on démarre le deep work" / "on demarre le deep work" (faute)
"je vais travailler sérieusement" / "j'vais travaiiler serieusement" (sms + fautes)
"active le mode travail" / "active le mode travaiil" (faute)
"je me concentre sur mon travail" / "j'me concentre sur mon travaiil" (sms + faute)
"démarre une session productive" / "demarre une session productive" (faute)
"je commence à bosser" / "je comence à bosser" (faute)
"c'est l'heure du focus" / "c l'heure du focus" (sms)
"je lance le mode travail" / "je lance le mode travaiil" (faute)
"on commence maintenant" / "on comence mnt" (sms + faute)
"je démarre ma session" / "je demarre ma session" (faute)
"je me mets au travail" / "j'me mets au travaiil" (sms + faute)
"active une session de deep work" / "active une session de deep work" (normal)
"je vais me concentrer maintenant" / "j'vais me concentrer mnt" (sms)
"démarre le travail" / "demarre le travaiil" (faute)
"je commence ma session" / "je comence ma session" (faute)
"c'est parti pour bosser" / "c parti pour bosser" (sms)
"je me lance dans le travail" / "j'me lance dans le travaiil" (sms + faute)
"on démarre une session" / "on demarre une session" (faute)
"je vais travailler en mode focus" / "j'vais travaiiler en mode focus" (sms + fautes)
"démarre maintenant" / "demarre mnt" (sms + faute)
"je commence le deep work" / "je comence le deep work" (faute)
"active le mode concentration" / "active le mode concentration" (normal)
"je me mets en mode travail" / "j'me mets en mode travaiil" (sms + faute)
"c'est l'heure de se concentrer" / "c l'heure de se concentrer" (sms)
"je démarre mon travail" / "je demarre mon travaiil" (fautes)
"lance une session maintenant" / "lance une session mnt" (sms)
"je vais bosser sérieusement" / "j'vais bosser serieusement" (sms + faute)
"on commence le travail" / "on comence le travaiil" (fautes)
"je me concentre" / "j'me concentre" (sms)
"démarre une session de focus" / "demarre une session de focus" (faute)
"je commence à me concentrer" / "je comence à me concentrer" (faute)
"c'est parti je travaille" / "c parti j'travaiile" (sms + fautes)
"je lance le mode deep work" / "je lance le mode deep work" (normal)
"active maintenant" / "active mnt" (sms)
"je me mets au boulot maintenant" / "j'me mets au boulot mnt" (sms)
"on démarre maintenant" / "on demarre mnt" (sms + faute)
"je vais travailler" / "j'vais travaiiler" (sms + faute)
"démarre le deep work" / "demarre le deep work" (faute)
"je commence ma journée de travail" / "je comence ma journee de travaiil" (fautes)
"c'est l'heure" / "c l'heure" (sms)
"je me concentre sur mon boulot" / "j'me concentre sur mon boulot" (sms)
"lance le mode travail" / "lance le mode travaiil" (faute)
"je démarre en mode focus" / "je demarre en mode focus" (faute)
"active une session productive maintenant" / "active une session productive mnt" (sms)
"je vais me mettre au travail" / "j'vais me mettre au travaiil" (sms + faute)
"on commence" / "on comence" (faute)
"je lance maintenant" / "je lance mnt" (sms)
"démarre ma session" / "demarre ma session" (faute)
"je me mets en mode concentration" / "j'me mets en mode concentration" (sms)
"c'est parti pour le travail" / "c parti pour le travaiil" (sms + faute)
"je commence en mode focus" / "je comence en mode focus" (faute)
"active le deep work" / "active le deep work" (normal)
"je vais bosser maintenant" / "j'vais bosser mnt" (sms)
"on démarre le travail" / "on demarre le travaiil" (fautes)
"je me concentre maintenant" / "j'me concentre mnt" (sms)
"lance une session de focus" / "lance une session de focus" (normal)
"je démarre maintenant" / "je demarre mnt" (sms + faute)
"active maintenant une session" / "active mnt une session" (sms)
"je vais commencer à travailler" / "j'vais comencer à travaiiler" (sms + fautes)
"on commence le deep work" / "on comence le deep work" (faute)
"je me mets au travail maintenant" / "j'me mets au travaiil mnt" (sms + fautes)
"c'est l'heure de bosser" / "c l'heure de bosser" (sms)
"je lance le travail" / "je lance le travaiil" (faute)
"démarre en mode concentration" / "demarre en mode concentration" (faute)
"je commence le mode focus" / "je comence le mode focus" (faute)
"active une session maintenant" / "active une session mnt" (sms)
"je vais me concentrer sur le travail" / "j'vais me concentrer sur le travaiil" (sms + faute)
"on démarre en mode focus" / "on demarre en mode focus" (faute)
"je me concentre sur mon travail" / "j'me concentre sur mon travaiil" (sms + faute)
"lance maintenant" / "lance mnt" (sms)
"je démarre le mode travail" / "je demarre le mode travaiil" (fautes)
"c'est parti je commence" / "c parti je comence" (sms + faute)
"je vais lancer une session" / "j'vais lancer une session" (sms)
"active le mode focus maintenant" / "active le mode focus mnt" (sms)
"on commence en mode concentration" / "on comence en mode concentration" (faute)
"je me mets en mode deep work" / "j'me mets en mode deep work" (sms)
"démarre le mode concentration" / "demarre le mode concentration" (faute)
"je commence le travail maintenant" / "je comence le travaiil mnt" (fautes + sms)
"c'est l'heure de commencer" / "c l'heure de comencer" (sms + faute)
"je lance en mode focus" / "je lance en mode focus" (normal)
"active une session de travail" / "active une session de travaiil" (faute)
"je vais démarrer" / "j'vais demarrer" (sms + faute)
"on démarre maintenant" / "on demarre mnt" (sms + faute)
"je me concentre en mode focus" / "j'me concentre en mode focus" (sms)
"lance le deep work" / "lance le deep work" (normal)
"je démarre une session de focus" / "je demarre une session de focus" (faute)
"active maintenant le mode travail" / "active mnt le mode travaiil" (sms + fautes)
"je commence maintenant" / "je comence mnt" (sms + faute)
"c'est parti pour le deep work" / "c parti pour le deep work" (sms)
"je vais activer une session" / "j'vais activer une session" (sms)
"on commence le mode focus" / "on comence le mode focus" (faute)
"je me mets au boulot maintenant" / "j'me mets au boulot mnt" (sms)
"démarre une session maintenant" / "demarre une session mnt" (sms + faute)
"je lance le mode concentration" / "je lance le mode concentration" (normal)
"active le travail" / "active le travaiil" (faute)
"je vais commencer maintenant" / "j'vais comencer mnt" (sms + faute)
"on démarre en mode focus" / "on demarre en mode focus" (faute)
"je me concentre maintenant" / "j'me concentre mnt" (sms)
"lance maintenant une session" / "lance mnt une session" (sms)
"je démarre le deep work maintenant" / "je demarre le deep work mnt" (fautes + sms)
"c'est l'heure de travailler maintenant" / "c l'heure de travaiiler mnt" (sms + fautes)
"je commence en mode deep work" / "je comence en mode deep work" (faute)
"active maintenant" / "active mnt" (sms)
"je vais me mettre au travail" / "j'vais me mettre au travaiil" (sms + faute)
"on commence maintenant" / "on comence mnt" (sms + faute)
"je me mets en mode focus maintenant" / "j'me mets en mode focus mnt" (sms)
"démarre maintenant" / "demarre mnt" (sms + faute)
"je lance une session de deep work" / "je lance une session de deep work" (normal)
"active le mode deep work" / "active le mode deep work" (normal)
"je vais commencer le travail" / "j'vais comencer le travaiil" (sms + fautes)
"on démarre une session" / "on demarre une session" (faute)
"je me concentre sur le travail maintenant" / "j'me concentre sur le travaiil mnt" (sms + fautes)

=== START_DEEPWORK_WITH_TASK ===
"je vais commencer la tâche 1" / "je vais commencer la tâche 1" (faute)
"je vais commencer la tâche 2" / "je vais commencer la tâche 2" (faute)
"je vais commencer la tâche 3" / "je vais commencer la tâche 3" (faute)
"je vais commencer la tâche 4" / "je vais commencer la tâche 4" (faute)
"je vais commencer la tâche 5" / "je vais commencer la tâche 5" (faute)
"je vais commencer la tache 1" / "je vais commencer la tache 1" (faute)
"je vais commencer la tache 2" / "je vais commencer la tache 2" (faute)
"je vais commencer la tache 3" / "je vais commencer la tache 3" (faute)
"je vais commencer la tache 4" / "je vais commencer la tache 4" (faute)
"je vais commencer la tache 5" / "je vais commencer la tache 5" (faute)
"je vais commencer tâche 1" / "je vais commencer tâche 1" (faute)
"je vais commencer tâche 2" / "je vais commencer tâche 2" (faute)
"je vais commencer tâche 3" / "je vais commencer tâche 3" (faute)
"je vais commencer tâche 4" / "je vais commencer tâche 4" (faute)
"je vais commencer tâche 5" / "je vais commencer tâche 5" (faute)
"je vais commencer tache 1" / "je vais commencer tache 1" (faute)
"je vais commencer tache 2" / "je vais commencer tache 2" (faute)
"je vais commencer tache 3" / "je vais commencer tache 3" (faute)
"je vais commencer tache 4" / "je vais commencer tache 4" (faute)
"je vais commencer tache 5" / "je vais commencer tache 5" (faute)
"je vais faire la tâche 1" / "je vais faire la tâche 1" (faute)
"je vais faire la tâche 2" / "je vais faire la tâche 2" (faute)
"je vais faire la tâche 3" / "je vais faire la tâche 3" (faute)
"je vais faire la tâche 4" / "je vais faire la tâche 4" (faute)
"je vais faire la tâche 5" / "je vais faire la tâche 5" (faute)
"je vais faire la tache 1" / "je vais faire la tache 1" (faute)
"je vais faire la tache 2" / "je vais faire la tache 2" (faute)
"je vais faire la tache 3" / "je vais faire la tache 3" (faute)
"je vais faire la tache 4" / "je vais faire la tache 4" (faute)
"je vais faire la tache 5" / "je vais faire la tache 5" (faute)
"je vais travailler sur la tâche 1" / "je vais travailler sur la tâche 1" (faute)
"je vais travailler sur la tâche 2" / "je vais travailler sur la tâche 2" (faute)
"je vais travailler sur la tâche 3" / "je vais travailler sur la tâche 3" (faute)
"je vais travailler sur la tâche 4" / "je vais travailler sur la tâche 4" (faute)
"je vais travailler sur la tâche 5" / "je vais travailler sur la tâche 5" (faute)
"je vais travailler sur la tache 1" / "je vais travailler sur la tache 1" (faute)
"je vais travailler sur la tache 2" / "je vais travailler sur la tache 2" (faute)
"je vais travailler sur la tache 3" / "je vais travailler sur la tache 3" (faute)
"je vais travailler sur la tache 4" / "je vais travailler sur la tache 4" (faute)
"je vais travailler sur la tache 5" / "je vais travailler sur la tache 5" (faute)
"je vais démarrer la tâche 1" / "je vais demarrer la tâche 1" (faute)
"je vais démarrer la tâche 2" / "je vais demarrer la tâche 2" (faute)
"je vais démarrer la tâche 3" / "je vais demarrer la tâche 3" (faute)
"je vais démarrer la tâche 4" / "je vais demarrer la tâche 4" (faute)
"je vais démarrer la tâche 5" / "je vais demarrer la tâche 5" (faute)
"je vais démarrer la tache 1" / "je vais demarrer la tache 1" (faute)
"je vais démarrer la tache 2" / "je vais demarrer la tache 2" (faute)
"je vais démarrer la tache 3" / "je vais demarrer la tache 3" (faute)
"je vais démarrer la tache 4" / "je vais demarrer la tache 4" (faute)
"je vais démarrer la tache 5" / "je vais demarrer la tache 5" (faute)
"je commence la tâche 1" / "je commence la tâche 1" (faute)
"je commence la tâche 2" / "je commence la tâche 2" (faute)
"je commence la tâche 3" / "je commence la tâche 3" (faute)
"je commence la tâche 4" / "je commence la tâche 4" (faute)
"je commence la tâche 5" / "je commence la tâche 5" (faute)
"je commence la tache 1" / "je commence la tache 1" (faute)
"je commence la tache 2" / "je commence la tache 2" (faute)
"je commence la tache 3" / "je commence la tache 3" (faute)
"je commence la tache 4" / "je commence la tache 4" (faute)
"je commence la tache 5" / "je commence la tache 5" (faute)
"je démarre la tâche 1" / "je demarre la tâche 1" (faute)
"je démarre la tâche 2" / "je demarre la tâche 2" (faute)
"je démarre la tâche 3" / "je demarre la tâche 3" (faute)
"je démarre la tâche 4" / "je demarre la tâche 4" (faute)
"je démarre la tâche 5" / "je demarre la tâche 5" (faute)
"je démarre la tache 1" / "je demarre la tache 1" (faute)
"je démarre la tache 2" / "je demarre la tache 2" (faute)
"je démarre la tache 3" / "je demarre la tache 3" (faute)
"je démarre la tache 4" / "je demarre la tache 4" (faute)
"je démarre la tache 5" / "je demarre la tache 5" (faute)
"je fais la tâche 1" / "je fais la tâche 1" (faute)
"je fais la tâche 2" / "je fais la tâche 2" (faute)
"je fais la tâche 3" / "je fais la tâche 3" (faute)
"je fais la tâche 4" / "je fais la tâche 4" (faute)
"je fais la tâche 5" / "je fais la tâche 5" (faute)
"je fais la tache 1" / "je fais la tache 1" (faute)
"je fais la tache 2" / "je fais la tache 2" (faute)
"je fais la tache 3" / "je fais la tache 3" (faute)
"je fais la tache 4" / "je fais la tache 4" (faute)
"je fais la tache 5" / "je fais la tache 5" (faute)
"je travaille sur la tâche 1" / "je travaille sur la tâche 1" (faute)
"je travaille sur la tâche 2" / "je travaille sur la tâche 2" (faute)
"je travaille sur la tâche 3" / "je travaille sur la tâche 3" (faute)
"je travaille sur la tâche 4" / "je travaille sur la tâche 4" (faute)
"je travaille sur la tâche 5" / "je travaille sur la tâche 5" (faute)
"je travaille sur la tache 1" / "je travaille sur la tache 1" (faute)
"je travaille sur la tache 2" / "je travaille sur la tache 2" (faute)
"je travaille sur la tache 3" / "je travaille sur la tache 3" (faute)
"je travaille sur la tache 4" / "je travaille sur la tache 4" (faute)
"je travaille sur la tache 5" / "je travaille sur la tache 5" (faute)
"commencer la tâche 1" / "commencer la tâche 1" (faute)
"commencer la tâche 2" / "commencer la tâche 2" (faute)
"commencer la tâche 3" / "commencer la tâche 3" (faute)
"commencer la tâche 4" / "commencer la tâche 4" (faute)
"commencer la tâche 5" / "commencer la tâche 5" (faute)
"commencer la tache 1" / "commencer la tache 1" (faute)
"commencer la tache 2" / "commencer la tache 2" (faute)
"commencer la tache 3" / "commencer la tache 3" (faute)
"commencer la tache 4" / "commencer la tache 4" (faute)
"commencer la tache 5" / "commencer la tache 5" (faute)
"je vais commencer Finaliser l'UX" / "je vais commencer Finaliser l'UX" (normal)
"je vais commencer Intégrer l'authentification" / "je vais commencer Integrer l'authentification" (faute)
"je vais commencer Réparer le bug" / "je vais commencer Reparer le bug" (faute)
"je vais commencer Créer le design" / "je vais commencer Creer le design" (faute)
"je vais commencer Écrire la documentation" / "je vais commencer Ecrire la documentation" (faute)
"je vais commencer Tester l'application" / "j'vais commencer Tester l'application" (sms)
"je vais commencer Optimiser les performances" / "j'vais commencer Optimiser les performances" (sms)
"je vais commencer Refactoriser le code" / "j'vais commencer Refactoriser le code" (sms)
"je vais commencer Mettre à jour la base de données" / "j'vais commencer Mettre a jour la base de donnees" (sms + fautes)
"je vais commencer Déployer en production" / "j'vais commencer Deployer en production" (sms + faute)

=== END_DEEPWORK ===
"je termine la session" / "je termine la session" (normal)
"c'est terminé" / "c terminé" (sms)
"fini" / "fini" (normal)
"stop" / "stop" (normal)
"ok c'est fait" / "ok c fait" (sms)
"terminé" / "terminé" (normal)
"j'ai fini la session" / "j'ai fini la session" (normal)
"c'est bon j'ai terminé" / "c bon j'ai terminé" (sms)
"je finis maintenant" / "je finis mnt" (sms)
"arrête la session" / "arrete la session" (faute)
"je clôture ma session" / "je cloture ma session" (normal)
"c'est fini" / "c fini" (sms)
"terminé pour aujourd'hui" / "terminé pour aujourdhui" (faute)
"je stoppe" / "je stoppe" (normal)
"fin de session" / "fin de session" (normal)
"j'arrête maintenant" / "j'arrete mnt" (sms + faute)
"c'est terminé pour moi" / "c terminé pour moi" (sms)
"je finis le travail" / "je finis le travaiil" (faute)
"arrêt de la session" / "arret de la session" (faute)
"je termine maintenant" / "je termine mnt" (sms)
"c'est bon j'ai fini" / "c bon j'ai fini" (sms)
"fini pour aujourd'hui" / "fini pour aujourdhui" (faute)
"je clôture maintenant" / "je cloture mnt" (sms)
"arrête maintenant" / "arrete mnt" (sms + faute)
"terminé le travail" / "terminé le travaiil" (faute)
"je stoppe la session" / "je stoppe la session" (normal)
"c'est fini maintenant" / "c fini mnt" (sms)
"j'ai terminé ma session" / "j'ai terminé ma session" (normal)
"fin de travail" / "fin de travaiil" (faute)
"je termine le deep work" / "je termine le deep work" (normal)
"arrêt maintenant" / "arret mnt" (sms + faute)
"c'est bon terminé" / "c bon terminé" (sms)
"je finis ma session" / "je finis ma session" (normal)
"terminé pour l'instant" / "terminé pour l'instant" (normal)
"je clôture le travail" / "je cloture le travaiil" (faute)
"arrête la session maintenant" / "arrete la session mnt" (sms + fautes)
"c'est fini pour aujourd'hui" / "c fini pour aujourdhui" (sms + faute)
"je stoppe maintenant" / "je stoppe mnt" (sms)
"j'ai fini maintenant" / "j'ai fini mnt" (sms)
"fin de session maintenant" / "fin de session mnt" (sms)
"je termine le travail" / "je termine le travaiil" (faute)
"arrêt de session" / "arret de session" (faute)
"c'est terminé maintenant" / "c terminé mnt" (sms)
"je finis pour aujourd'hui" / "je finis pour aujourdhui" (faute)
"terminé la session" / "terminé la session" (normal)
"je clôture maintenant" / "je cloture mnt" (sms)
"arrête maintenant la session" / "arrete mnt la session" (sms + faute)
"c'est bon j'ai terminé maintenant" / "c bon j'ai terminé mnt" (sms)
"fini maintenant" / "fini mnt" (sms)
"je stoppe la session maintenant" / "je stoppe la session mnt" (sms)
"j'arrête la session" / "j'arrete la session" (faute)
"c'est fini pour moi" / "c fini pour moi" (sms)
"je termine pour aujourd'hui" / "je termine pour aujourdhui" (faute)
"arrêt maintenant" / "arret mnt" (sms + faute)
"terminé maintenant" / "terminé mnt" (sms)
"je finis le deep work" / "je finis le deep work" (normal)
"c'est bon fini" / "c bon fini" (sms)
"je clôture la session maintenant" / "je cloture la session mnt" (sms)
"arrête le travail" / "arrete le travaiil" (fautes)
"c'est terminé pour aujourd'hui" / "c terminé pour aujourdhui" (sms + faute)
"je stoppe maintenant" / "je stoppe mnt" (sms)
"j'ai terminé maintenant" / "j'ai terminé mnt" (sms)
"fin maintenant" / "fin mnt" (sms)
"je termine ma session maintenant" / "je termine ma session mnt" (sms)
"arrêt de la session maintenant" / "arret de la session mnt" (sms + faute)
"c'est fini j'ai terminé" / "c fini j'ai terminé" (sms)
"je finis maintenant" / "je finis mnt" (sms)
"terminé le deep work" / "terminé le deep work" (normal)
"je clôture maintenant" / "je cloture mnt" (sms)
"arrête maintenant" / "arrete mnt" (sms + faute)
"c'est bon c'est fini" / "c bon c fini" (sms)
"je stoppe le travail" / "je stoppe le travaiil" (faute)
"j'arrête maintenant" / "j'arrete mnt" (sms + faute)
"c'est terminé le travail" / "c terminé le travaiil" (sms + faute)
"je termine maintenant" / "je termine mnt" (sms)
"fin de travail maintenant" / "fin de travaiil mnt" (sms + faute)
"arrêt maintenant" / "arret mnt" (sms + faute)
"terminé maintenant" / "terminé mnt" (sms)
"je finis la session maintenant" / "je finis la session mnt" (sms)
"c'est fini maintenant" / "c fini mnt" (sms)
"je clôture le travail maintenant" / "je cloture le travaiil mnt" (sms + fautes)
"arrête la session" / "arrete la session" (faute)
"c'est bon terminé maintenant" / "c bon terminé mnt" (sms)
"je stoppe maintenant" / "je stoppe mnt" (sms)
"j'ai fini maintenant" / "j'ai fini mnt" (sms)
"fin maintenant" / "fin mnt" (sms)
"je termine le travail maintenant" / "je termine le travaiil mnt" (sms + fautes)
"arrêt de session maintenant" / "arret de session mnt" (sms + faute)
"c'est terminé maintenant" / "c terminé mnt" (sms)
"je finis maintenant" / "je finis mnt" (sms)
"terminé la session maintenant" / "terminé la session mnt" (sms)
"je clôture maintenant" / "je cloture mnt" (sms)
"arrête maintenant" / "arrete mnt" (sms + faute)
"c'est fini terminé" / "c fini terminé" (sms)
"je stoppe la session maintenant" / "je stoppe la session mnt" (sms)
"j'arrête maintenant" / "j'arrete mnt" (sms + faute)
"c'est bon fini maintenant" / "c bon fini mnt" (sms)
"je termine maintenant" / "je termine mnt" (sms)
"fin de session maintenant" / "fin de session mnt" (sms)
"arrêt maintenant" / "arret mnt" (sms + faute)
"terminé maintenant" / "terminé mnt" (sms)
"je finis maintenant" / "je finis mnt" (sms)
"c'est terminé fini" / "c terminé fini" (sms)
"je clôture la session maintenant" / "je cloture la session mnt" (sms)
"arrête le travail maintenant" / "arrete le travaiil mnt" (sms + fautes)
"c'est fini maintenant" / "c fini mnt" (sms)
"je stoppe maintenant" / "je stoppe mnt" (sms)
"j'ai terminé maintenant" / "j'ai terminé mnt" (sms)
"fin maintenant" / "fin mnt" (sms)
"je termine la session maintenant" / "je termine la session mnt" (sms)
"arrêt de la session maintenant" / "arret de la session mnt" (sms + faute)
"c'est bon terminé maintenant" / "c bon terminé mnt" (sms)
"je finis maintenant" / "je finis mnt" (sms)
"terminé maintenant" / "terminé mnt" (sms)
"je clôture maintenant" / "je cloture mnt" (sms)
"arrête maintenant" / "arrete mnt" (sms + faute)
"c'est fini maintenant" / "c fini mnt" (sms)
"je stoppe maintenant" / "je stoppe mnt" (sms)
"j'arrête maintenant" / "j'arrete mnt" (sms + faute)
"c'est terminé maintenant" / "c terminé mnt" (sms)
"je termine maintenant" / "je termine mnt" (sms)
"fin maintenant" / "fin mnt" (sms)

=== END_DEEPWORK_WITH_TASK ===
"j'ai fini la tâche" / "j'ai fini la tâche" (faute)
"j'ai fini la tâche" / "j'aifinilatâche" (sms)
"j'ai fini la tache" / "j'ai fini la tache" (faute)
"j'ai fini la tache" / "j'aifinilatache" (sms)
"j'ai terminé la tâche" / "j'ai termine la tâche" (faute)
"j'ai terminé la tâche" / "j'aiterminélatâche" (sms)
"j'ai terminé la tache" / "j'ai termine la tache" (faute)
"j'ai terminé la tache" / "j'aiterminélatache" (sms)
"j'ai complété la tâche" / "j'ai complete la tâche" (faute)
"j'ai complété la tâche" / "j'aicomplétélatâche" (sms)
"j'ai complété la tache" / "j'ai complete la tache" (faute)
"j'ai complété la tache" / "j'aicomplétélatache" (sms)
"je finis la tâche" / "je finis la tâche" (faute)
"je finis la tâche" / "j'finislatâche" (sms)
"je finis la tache" / "je finis la tache" (faute)
"je finis la tache" / "j'finislatache" (sms)
"je termine la tâche" / "je termine la tâche" (faute)
"je termine la tâche" / "j'terminelatâche" (sms)
"je termine la tache" / "je termine la tache" (faute)
"je termine la tache" / "j'terminelatache" (sms)
"je complète la tâche" / "je complete la tâche" (faute)
"je complète la tâche" / "j'complètelatâche" (sms)
"je complète la tache" / "je complete la tache" (faute)
"je complète la tache" / "j'complètelatache" (sms)
"fini la tâche" / "fini la tâche" (faute)
"fini la tâche" / "finilatâche" (sms)
"fini la tache" / "fini la tache" (faute)
"fini la tache" / "finilatache" (sms)
"terminé la tâche" / "termine la tâche" (faute)
"terminé la tâche" / "terminélatâche" (sms)
"terminé la tache" / "termine la tache" (faute)
"terminé la tache" / "terminélatache" (sms)
"complété la tâche" / "complete la tâche" (faute)
"complété la tâche" / "complétélatâche" (sms)
"complété la tache" / "complete la tache" (faute)
"complété la tache" / "complétélatache" (sms)
"j'ai fini" / "j'ai fini" (faute)
"j'ai fini" / "j'aifini" (sms)
"j'ai terminé" / "j'ai termine" (faute)
"j'ai terminé" / "j'aiterminé" (sms)
"j'ai complété" / "j'ai complete" (faute)
"j'ai complété" / "j'aicomplété" (sms)
"je finis" / "je finis" (faute)
"je finis" / "j'finis" (sms)
"je termine" / "je termine" (faute)
"je termine" / "j'termine" (sms)
"je complète" / "je complete" (faute)
"je complète" / "j'complète" (sms)
"fini" / "fini" (faute)
"fini" / "fini" (sms)
"terminé" / "termine" (faute)
"terminé" / "terminé" (sms)
"complété" / "complete" (faute)
"complété" / "complété" (sms)
"c'est fait" / "c'est fait" (faute)
"c'est fait" / "c'estfait" (sms)
"c'est terminé" / "c'est termine" (faute)
"c'est terminé" / "c'estterminé" (sms)
"c'est fini" / "c'est fini" (faute)
"c'est fini" / "c'estfini" (sms)
"c'est complété" / "c'est complete" (faute)
"c'est complété" / "c'estcomplété" (sms)
"ok c'est fait" / "ok c'est fait" (faute)
"ok c'est fait" / "okc'estfait" (sms)
"ok c'est terminé" / "ok c'est termine" (faute)
"ok c'est terminé" / "okc'estterminé" (sms)
"ok c'est fini" / "ok c'est fini" (faute)
"ok c'est fini" / "okc'estfini" (sms)
"j'ai fini maintenant" / "j'ai fini maintenant" (faute)
"j'ai fini maintenant" / "j'aifinimnt" (sms)
"j'ai terminé maintenant" / "j'ai termine maintenant" (faute)
"j'ai terminé maintenant" / "j'aiterminémnt" (sms)
"je finis maintenant" / "je finis maintenant" (faute)
"je finis maintenant" / "j'finismnt" (sms)
"je termine maintenant" / "je termine maintenant" (faute)
"je termine maintenant" / "j'terminemnt" (sms)
"fini maintenant" / "fini maintenant" (faute)
"fini maintenant" / "finimnt" (sms)
"terminé maintenant" / "termine maintenant" (faute)
"terminé maintenant" / "terminémnt" (sms)
"j'ai fini la tâche 1" / "j'ai fini la tâche 1" (faute)
"j'ai fini la tâche 2" / "j'ai fini la tâche 2" (faute)
"j'ai fini la tâche 3" / "j'ai fini la tâche 3" (faute)
"j'ai fini la tâche 4" / "j'ai fini la tâche 4" (faute)
"j'ai fini la tâche 5" / "j'ai fini la tâche 5" (faute)
"j'ai fini la tache 1" / "j'ai fini la tache 1" (faute)
"j'ai fini la tache 2" / "j'ai fini la tache 2" (faute)
"j'ai fini la tache 3" / "j'ai fini la tache 3" (faute)
"j'ai fini la tache 4" / "j'ai fini la tache 4" (faute)
"j'ai fini la tache 5" / "j'ai fini la tache 5" (faute)
"j'ai terminé la tâche 1" / "j'ai termine la tâche 1" (faute)
"j'ai terminé la tâche 2" / "j'ai termine la tâche 2" (faute)
"j'ai terminé la tâche 3" / "j'ai termine la tâche 3" (faute)
"j'ai terminé la tâche 4" / "j'ai termine la tâche 4" (faute)
"j'ai terminé la tâche 5" / "j'ai termine la tâche 5" (faute)
"j'ai terminé la tache 1" / "j'ai termine la tache 1" (faute)
"j'ai terminé la tache 2" / "j'ai termine la tache 2" (faute)
"j'ai terminé la tache 3" / "j'ai termine la tache 3" (faute)
"j'ai terminé la tache 4" / "j'ai termine la tache 4" (faute)
"j'ai terminé la tache 5" / "j'ai termine la tache 5" (faute)

=== PAUSE_DEEPWORK ===
"je fais une pause" / "je fais une pause" (faute)
"je fais une pause" / "j'faisunepause" (sms)
"je fais pause" / "je fais pause" (faute)
"je fais pause" / "j'faispause" (sms)
"je prends une pause" / "je prends une pause" (faute)
"je prends une pause" / "j'prendsunepause" (sms)
"je prends pause" / "je prends pause" (faute)
"je prends pause" / "j'prendspause" (sms)
"pause" / "pause" (faute)
"pause" / "pause" (sms)
"pause session" / "pause session" (faute)
"pause session" / "pausesession" (sms)
"pause la session" / "pause la session" (faute)
"pause la session" / "pauselasession" (sms)
"mettre en pause" / "mettre en pause" (faute)
"mettre en pause" / "mettreenpause" (sms)
"mets en pause" / "mets en pause" (faute)
"mets en pause" / "metsenpause" (sms)
"mettre pause" / "mettre pause" (faute)
"mettre pause" / "mettrepause" (sms)
"mets pause" / "mets pause" (faute)
"mets pause" / "metspause" (sms)
"je pause" / "je pause" (faute)
"je pause" / "j'pause" (sms)
"je mets en pause" / "je mets en pause" (faute)
"je mets en pause" / "j'metsenpause" (sms)
"je mets pause" / "je mets pause" (faute)
"je mets pause" / "j'metspause" (sms)
"on fait une pause" / "on fait une pause" (faute)
"on fait une pause" / "onfaitunepause" (sms)
"on fait pause" / "on fait pause" (faute)
"on fait pause" / "onfaitpause" (sms)
"on prend une pause" / "on prend une pause" (faute)
"on prend une pause" / "onprendunepause" (sms)
"on prend pause" / "on prend pause" (faute)
"on prend pause" / "onprendpause" (sms)
"pause maintenant" / "pause maintenant" (faute)
"pause maintenant" / "pausemnt" (sms)
"pause la session maintenant" / "pause la session maintenant" (faute)
"pause la session maintenant" / "pauselasessionmnt" (sms)
"je fais une pause maintenant" / "je fais une pause maintenant" (faute)
"je fais une pause maintenant" / "j'faisunepausemnt" (sms)
"je prends une pause maintenant" / "je prends une pause maintenant" (faute)
"je prends une pause maintenant" / "j'prendsunepausemnt" (sms)
"mets en pause maintenant" / "mets en pause maintenant" (faute)
"mets en pause maintenant" / "metsenpausemnt" (sms)
"pause s'il te plaît" / "pause s'il te plait" (faute)
"pause s'il te plaît" / "pauses'ilteplaît" (sms)
"pause stp" / "pause stp" (faute)
"pause stp" / "pausestp" (sms)
"pause svp" / "pause svp" (faute)
"pause svp" / "pausesvp" (sms)
"je fais pause maintenant" / "je fais pause maintenant" (faute)
"je fais pause maintenant" / "j'faispausemnt" (sms)
"je prends pause maintenant" / "je prends pause maintenant" (faute)
"je prends pause maintenant" / "j'prendspausemnt" (sms)
"mets pause maintenant" / "mets pause maintenant" (faute)
"mets pause maintenant" / "metspausemnt" (sms)
"je pause maintenant" / "je pause maintenant" (faute)
"je pause maintenant" / "j'pausemnt" (sms)
"on fait pause maintenant" / "on fait pause maintenant" (faute)
"on fait pause maintenant" / "onfaitpausemnt" (sms)
"on prend pause maintenant" / "on prend pause maintenant" (faute)
"on prend pause maintenant" / "onprendpausemnt" (sms)
"pause la session" / "pause la session" (faute)
"pause la session" / "pauselasession" (sms)
"pause le deep work" / "pause le deep work" (faute)
"pause le deep work" / "pauseledeepwork" (sms)
"pause le travail" / "pause le travail" (faute)
"pause le travail" / "pauseletravail" (sms)
"je fais une pause dans le travail" / "je fais une pause dans le travail" (faute)
"je fais une pause dans le travail" / "j'faisunepausedansletravail" (sms)
"je prends une pause dans le travail" / "je prends une pause dans le travail" (faute)
"je prends une pause dans le travail" / "j'prendsunepausedansletravail" (sms)
"mettre en pause le travail" / "mettre en pause le travail" (faute)
"mettre en pause le travail" / "mettreenpauseletravail" (sms)
"mets en pause le travail" / "mets en pause le travail" (faute)
"mets en pause le travail" / "metsenpauseletravail" (sms)
"je mets en pause le travail" / "je mets en pause le travail" (faute)
"je mets en pause le travail" / "j'metsenpauseletravail" (sms)
"on fait une pause dans le travail" / "on fait une pause dans le travail" (faute)
"on fait une pause dans le travail" / "onfaitunepausedansletravail" (sms)
"on prend une pause dans le travail" / "on prend une pause dans le travail" (faute)
"on prend une pause dans le travail" / "onprendunepausedansletravail" (sms)
"pause le deep work maintenant" / "pause le deep work maintenant" (faute)
"pause le deep work maintenant" / "pauseledeepworkmnt" (sms)
"pause le travail maintenant" / "pause le travail maintenant" (faute)
"pause le travail maintenant" / "pauseletravailmnt" (sms)
"je fais une pause dans le deep work" / "je fais une pause dans le deep work" (faute)
"je fais une pause dans le deep work" / "j'faisunepausedansledeepwork" (sms)
"je prends une pause dans le deep work" / "je prends une pause dans le deep work" (faute)
"je prends une pause dans le deep work" / "j'prendsunepausedansledeepwork" (sms)
"mettre en pause le deep work" / "mettre en pause le deep work" (faute)
"mettre en pause le deep work" / "mettreenpauseledeepwork" (sms)
"mets en pause le deep work" / "mets en pause le deep work" (faute)
"mets en pause le deep work" / "metsenpauseledeepwork" (sms)
"je mets en pause le deep work" / "je mets en pause le deep work" (faute)
"je mets en pause le deep work" / "j'metsenpauseledeepwork" (sms)
"on fait une pause dans le deep work" / "on fait une pause dans le deep work" (faute)
"on fait une pause dans le deep work" / "onfaitunepausedansledeepwork" (sms)

=== RESUME_DEEPWORK ===
"je reprends" / "je reprends" (faute)
"je reprends" / "j'reprends" (sms)
"je reprend" / "je reprend" (faute)
"je reprend" / "j'reprend" (sms)
"reprends" / "reprends" (faute)
"reprends" / "reprends" (sms)
"reprend" / "reprend" (faute)
"reprend" / "reprend" (sms)
"je continue" / "je continue" (faute)
"je continue" / "j'continue" (sms)
"continue" / "continue" (faute)
"continue" / "continue" (sms)
"je relance" / "je relance" (faute)
"je relance" / "j'relance" (sms)
"relance" / "relance" (faute)
"relance" / "relance" (sms)
"je redémarre" / "je redemarre" (faute)
"je redémarre" / "j'redémarre" (sms)
"redémarre" / "redemarre" (faute)
"redémarre" / "redémarre" (sms)
"reprendre" / "reprendre" (faute)
"reprendre" / "reprendre" (sms)
"continuer" / "continuer" (faute)
"continuer" / "continuer" (sms)
"relancer" / "relancer" (faute)
"relancer" / "relancer" (sms)
"redémarrer" / "redemarrer" (faute)
"redémarrer" / "redémarrer" (sms)
"je reprends la session" / "je reprends la session" (faute)
"je reprends la session" / "j'reprendslasession" (sms)
"je reprend la session" / "je reprend la session" (faute)
"je reprend la session" / "j'reprendlasession" (sms)
"reprends la session" / "reprends la session" (faute)
"reprends la session" / "reprendslasession" (sms)
"reprend la session" / "reprend la session" (faute)
"reprend la session" / "reprendlasession" (sms)
"je continue la session" / "je continue la session" (faute)
"je continue la session" / "j'continuelasession" (sms)
"continue la session" / "continue la session" (faute)
"continue la session" / "continuelasession" (sms)
"je relance la session" / "je relance la session" (faute)
"je relance la session" / "j'relanclasession" (sms)
"relance la session" / "relance la session" (faute)
"relance la session" / "relanclasession" (sms)
"je redémarre la session" / "je redemarre la session" (faute)
"je redémarre la session" / "j'redémarrelasession" (sms)
"redémarre la session" / "redemarre la session" (faute)
"redémarre la session" / "redémarrelasession" (sms)
"reprendre la session" / "reprendre la session" (faute)
"reprendre la session" / "reprendrelasession" (sms)
"continuer la session" / "continuer la session" (faute)
"continuer la session" / "continuerlasession" (sms)
"relancer la session" / "relancer la session" (faute)
"relancer la session" / "relancerlasession" (sms)
"redémarrer la session" / "redemarrer la session" (faute)
"redémarrer la session" / "redémarrerlasession" (sms)
"je reprends maintenant" / "je reprends maintenant" (faute)
"je reprends maintenant" / "j'reprendsmnt" (sms)
"je reprend maintenant" / "je reprend maintenant" (faute)
"je reprend maintenant" / "j'reprendmnt" (sms)
"reprends maintenant" / "reprends maintenant" (faute)
"reprends maintenant" / "reprendsmnt" (sms)
"reprend maintenant" / "reprend maintenant" (faute)
"reprend maintenant" / "reprendmnt" (sms)
"je continue maintenant" / "je continue maintenant" (faute)
"je continue maintenant" / "j'continuemnt" (sms)
"continue maintenant" / "continue maintenant" (faute)
"continue maintenant" / "continuemnt" (sms)
"je relance maintenant" / "je relance maintenant" (faute)
"je relance maintenant" / "j'relancmnt" (sms)
"relance maintenant" / "relance maintenant" (faute)
"relance maintenant" / "relancmnt" (sms)
"je redémarre maintenant" / "je redemarre maintenant" (faute)
"je redémarre maintenant" / "j'redémarremnt" (sms)
"redémarre maintenant" / "redemarre maintenant" (faute)
"redémarre maintenant" / "redémarremnt" (sms)
"reprendre maintenant" / "reprendre maintenant" (faute)
"reprendre maintenant" / "reprendremnt" (sms)
"continuer maintenant" / "continuer maintenant" (faute)
"continuer maintenant" / "continuermnt" (sms)
"relancer maintenant" / "relancer maintenant" (faute)
"relancer maintenant" / "relancermnt" (sms)
"redémarrer maintenant" / "redemarrer maintenant" (faute)
"redémarrer maintenant" / "redémarrermnt" (sms)
"je reprends le travail" / "je reprends le travail" (faute)
"je reprends le travail" / "j'reprendsletravail" (sms)
"je reprend le travail" / "je reprend le travail" (faute)
"je reprend le travail" / "j'reprendletravail" (sms)
"reprends le travail" / "reprends le travail" (faute)
"reprends le travail" / "reprendsletravail" (sms)
"reprend le travail" / "reprend le travail" (faute)
"reprend le travail" / "reprendletravail" (sms)
"je continue le travail" / "je continue le travail" (faute)
"je continue le travail" / "j'continueletravail" (sms)
"continue le travail" / "continue le travail" (faute)
"continue le travail" / "continueletravail" (sms)
"je relance le travail" / "je relance le travail" (faute)
"je relance le travail" / "j'relancletravail" (sms)
"relance le travail" / "relance le travail" (faute)
"relance le travail" / "relancletravail" (sms)
"je redémarre le travail" / "je redemarre le travail" (faute)
"je redémarre le travail" / "j'redémarreletravail" (sms)
"redémarre le travail" / "redemarre le travail" (faute)
"redémarre le travail" / "redémarreletravail" (sms)
"reprendre le travail" / "reprendre le travail" (faute)
"reprendre le travail" / "reprendreletravail" (sms)
"continuer le travail" / "continuer le travail" (faute)
"continuer le travail" / "continuerletravail" (sms)
"relancer le travail" / "relancer le travail" (faute)
"relancer le travail" / "relancerletravail" (sms)
"redémarrer le travail" / "redemarrer le travail" (faute)
"redémarrer le travail" / "redémarrerletravail" (sms)
"je reprends le deep work" / "je reprends le deep work" (faute)
"je reprends le deep work" / "j'reprendsledeepwork" (sms)
"je reprend le deep work" / "je reprend le deep work" (faute)
"je reprend le deep work" / "j'reprendledeepwork" (sms)
"reprends le deep work" / "reprends le deep work" (faute)
"reprends le deep work" / "reprendsledeepwork" (sms)
"reprend le deep work" / "reprend le deep work" (faute)
"reprend le deep work" / "reprendledeepwork" (sms)
"je continue le deep work" / "je continue le deep work" (faute)
"je continue le deep work" / "j'continueledeepwork" (sms)
"continue le deep work" / "continue le deep work" (faute)
"continue le deep work" / "continueledeepwork" (sms)
"je relance le deep work" / "je relance le deep work" (faute)
"je relance le deep work" / "j'relancleedeepwork" (sms)
"relance le deep work" / "relance le deep work" (faute)
"relance le deep work" / "relancleedeepwork" (sms)
"je redémarre le deep work" / "je redemarre le deep work" (faute)
"je redémarre le deep work" / "j'redémarreledeepwork" (sms)
"redémarre le deep work" / "redemarre le deep work" (faute)
"redémarre le deep work" / "redémarreledeepwork" (sms)
"reprendre le deep work" / "reprendre le deep work" (faute)
"reprendre le deep work" / "reprendreledeepwork" (sms)
"continuer le deep work" / "continuer le deep work" (faute)
"continuer le deep work" / "continuerledeepwork" (sms)
"relancer le deep work" / "relancer le deep work" (faute)
"relancer le deep work" / "relancerledeepwork" (sms)
"redémarrer le deep work" / "redemarrer le deep work" (faute)
"redémarrer le deep work" / "redémarrerledeepwork" (sms)
"on reprend" / "on reprend" (faute)
"on reprends" / "on reprends" (faute)
"on continue" / "on continue" (faute)
"on relance" / "on relance" (faute)
"on redémarre" / "on redemarre" (faute)
"on reprend maintenant" / "on reprend maintenant" (faute)
"on reprends maintenant" / "on reprends maintenant" (faute)
"on continue maintenant" / "on continue maintenant" (faute)
"on relance maintenant" / "on relance maintenant" (faute)
"on redémarre maintenant" / "on redemarre maintenant" (faute)
"on reprend le travail" / "on reprend le travail" (faute)
"on reprends le travail" / "on reprends le travail" (faute)
"on continue le travail" / "on continue le travail" (faute)
"on relance le travail" / "on relance le travail" (faute)
"on redémarre le travail" / "on redemarre le travail" (faute)
"on reprend le deep work" / "on reprend le deep work" (faute)
"on reprends le deep work" / "on reprends le deep work" (faute)
"on continue le deep work" / "on continue le deep work" (faute)
"on relance le deep work" / "on relance le deep work" (faute)
"on redémarre le deep work" / "on redemarre le deep work" (faute)

=== PLAN_TOMORROW ===
"planifie demain" / "planifie demain" (faute)
"planifie demain" / "planifie dem1n" (sms)
"organise ma journée de demain" / "organise ma journee de demain" (faute)
"organise ma journée de demain" / "organise ma journee de dem1n" (sms)
"mes tâches de demain" / "mes taches de demain" (faute)
"mes tâches de demain" / "mes taches de dem1n" (sms)
"qu'est-ce que j'ai à faire demain" / "qu'est-ce que j'ai a faire demain" (faute)
"qu'est-ce que j'ai à faire demain" / "q'est-ce que j'ai à faire dem1n" (sms)
"qu'est-ce que j'ai à faire demain" / "q'est-ce que j'ai a faire dem1n" (sms + faute)
"aide-moi à organiser demain" / "aide-moi a organiser demain" (faute)
"aide-moi à organiser demain" / "aide-moi à organiser dem1n" (sms)
"aide-moi à organiser demain" / "aide-moi a organiser dem1n" (sms + faute)
"prépare ma journée de demain" / "prepare ma journee de demain" (faute)
"prépare ma journée de demain" / "prépare ma journee de dem1n" (sms)
"prépare ma journée de demain" / "prepare ma journee de dem1n" (sms + faute)
"organise demain pour moi" / "organise demain pour moi" (faute)
"organise demain pour moi" / "organise dem1n pour moi" (sms)
"qu'est-ce que je dois faire demain" / "qu'est-ce que je dois faire demain" (faute)
"qu'est-ce que je dois faire demain" / "q'est-ce que je dois faire dem1n" (sms)
"planifie ma journée de demain" / "planifie ma journee de demain" (faute)
"planifie ma journée de demain" / "planifie ma journee de dem1n" (sms)
"aide-moi à planifier demain" / "aide-moi a planifier demain" (faute)
"aide-moi à planifier demain" / "aide-moi à planifier dem1n" (sms)
"aide-moi à planifier demain" / "aide-moi a planifier dem1n" (sms + faute)
"organise mes tâches de demain" / "organise mes taches de demain" (faute)
"organise mes tâches de demain" / "organise mes taches de dem1n" (sms)
"prépare demain" / "prepare demain" (faute)
"prépare demain" / "prépare dem1n" (sms)
"prépare demain" / "prepare dem1n" (sms + faute)
"planifie ma journée demain" / "planifie ma journee demain" (faute)
"planifie ma journée demain" / "planifie ma journee dem1n" (sms)
"organise tout pour demain" / "organise tout pour demain" (faute)
"organise tout pour demain" / "organise tout pour dem1n" (sms)
"quelles sont mes tâches demain" / "quelles sont mes taches demain" (faute)
"quelles sont mes tâches demain" / "quelles sont mes taches dem1n" (sms)
"aide-moi pour demain" / "aide-moi pour demain" (faute)
"aide-moi pour demain" / "aide-moi pour dem1n" (sms)
"planifie mes activités de demain" / "planifie mes activites de demain" (faute)
"planifie mes activités de demain" / "planifie mes activités de dem1n" (sms)
"planifie mes activités de demain" / "planifie mes activites de dem1n" (sms + faute)
"organise ma journée demain" / "organise ma journee demain" (faute)
"organise ma journée demain" / "organise ma journee dem1n" (sms)
"prépare mes tâches de demain" / "prepare mes taches de demain" (faute)
"prépare mes tâches de demain" / "prépare mes taches de dem1n" (sms)
"prépare mes tâches de demain" / "prepare mes taches de dem1n" (sms + faute)
"planifie demain s'il te plaît" / "planifie demain s'il te plait" (faute)
"planifie demain s'il te plaît" / "planifie dem1n s'il te plaît" (sms)
"planifie demain s'il te plaît" / "planifie dem1n s'il te plait" (sms + faute)
"organise demain pour moi s'il te plaît" / "organise demain pour moi s'il te plait" (faute)
"organise demain pour moi s'il te plaît" / "organise dem1n pour moi s'il te plaît" (sms)
"organise demain pour moi s'il te plaît" / "organise dem1n pour moi s'il te plait" (sms + faute)
"aide-moi à organiser ma journée de demain" / "aide-moi a organiser ma journee de demain" (faute)
"aide-moi à organiser ma journée de demain" / "aide-moi à organiser ma journee de dem1n" (sms)
"aide-moi à organiser ma journée de demain" / "aide-moi a organiser ma journee de dem1n" (sms + faute)
"qu'est-ce que j'ai prévu demain" / "qu'est-ce que j'ai prevu demain" (faute)
"qu'est-ce que j'ai prévu demain" / "q'est-ce que j'ai prévu dem1n" (sms)
"qu'est-ce que j'ai prévu demain" / "q'est-ce que j'ai prevu dem1n" (sms + faute)
"planifie ma journée de demain s'il te plaît" / "planifie ma journee de demain s'il te plait" (faute)
"planifie ma journée de demain s'il te plaît" / "planifie ma journee de dem1n s'il te plaît" (sms)
"planifie ma journée de demain s'il te plaît" / "planifie ma journee de dem1n s'il te plait" (sms + faute)
"organise tout ce que j'ai à faire demain" / "organise tout ce que j'ai a faire demain" (faute)
"organise tout ce que j'ai à faire demain" / "organise tout ce que j'ai à faire dem1n" (sms)
"organise tout ce que j'ai à faire demain" / "organise tout ce que j'ai a faire dem1n" (sms + faute)
"prépare un planning pour demain" / "prepare un planning pour demain" (faute)
"prépare un planning pour demain" / "prépare un planning pour dem1n" (sms)
"prépare un planning pour demain" / "prepare un planning pour dem1n" (sms + faute)
"aide-moi à préparer demain" / "aide-moi a preparer demain" (faute)
"aide-moi à préparer demain" / "aide-moi à préparer dem1n" (sms)
"aide-moi à préparer demain" / "aide-moi a preparer dem1n" (sms + faute)
"planifie mes rendez-vous de demain" / "planifie mes rendez-vous de demain" (faute)
"planifie mes rendez-vous de demain" / "planifie mes rendez-vous de dem1n" (sms)
"organise ma semaine demain" / "organise ma semaine demain" (faute)
"organise ma semaine demain" / "organise ma semaine dem1n" (sms)
"qu'est-ce que je dois prévoir demain" / "qu'est-ce que je dois prevoir demain" (faute)
"qu'est-ce que je dois prévoir demain" / "q'est-ce que je dois prévoir dem1n" (sms)
"qu'est-ce que je dois prévoir demain" / "q'est-ce que je dois prevoir dem1n" (sms + faute)
"planifie demain matin" / "planifie demain matin" (faute)
"planifie demain matin" / "planifie dem1n matin" (sms)
"organise ma matinée de demain" / "organise ma matinee de demain" (faute)
"organise ma matinée de demain" / "organise ma matinée de dem1n" (sms)
"organise ma matinée de demain" / "organise ma matinee de dem1n" (sms + faute)
"aide-moi à planifier ma journée de demain" / "aide-moi a planifier ma journee de demain" (faute)
"aide-moi à planifier ma journée de demain" / "aide-moi à planifier ma journee de dem1n" (sms)
"aide-moi à planifier ma journée de demain" / "aide-moi a planifier ma journee de dem1n" (sms + faute)
"prépare ma liste pour demain" / "prepare ma liste pour demain" (faute)
"prépare ma liste pour demain" / "prépare ma liste pour dem1n" (sms)
"prépare ma liste pour demain" / "prepare ma liste pour dem1n" (sms + faute)
"planifie tout pour demain" / "planifie tout pour demain" (faute)
"planifie tout pour demain" / "planifie tout pour dem1n" (sms)
"organise mes priorités de demain" / "organise mes priorites de demain" (faute)
"organise mes priorités de demain" / "organise mes priorités de dem1n" (sms)
"organise mes priorités de demain" / "organise mes priorites de dem1n" (sms + faute)
"qu'est-ce que j'ai à faire demain matin" / "qu'est-ce que j'ai a faire demain matin" (faute)
"qu'est-ce que j'ai à faire demain matin" / "q'est-ce que j'ai à faire dem1n matin" (sms)
"qu'est-ce que j'ai à faire demain matin" / "q'est-ce que j'ai a faire dem1n matin" (sms + faute)
"planifie ma journée de demain matin" / "planifie ma journee de demain matin" (faute)
"planifie ma journée de demain matin" / "planifie ma journee de dem1n matin" (sms)
"aide-moi à organiser demain" / "aide-moi a organiser demain" (faute)
"aide-moi à organiser demain" / "aide-moi à organiser dem1n" (sms)
"aide-moi à organiser demain" / "aide-moi a organiser dem1n" (sms + faute)

=== JOURNAL ===
"note de ma journée" / "note de ma journee" (faute)
"raconter ma journée" / "raconter ma journee" (faute)
"journal" / "journal" (normal)
"récap de ma journée" / "recap de ma journee" (faute)

=== COMPLETE_TASK ===
"j'ai fini" / "j'ai fini" (faute)
"c'est fait" / "c'est fait" (faute)
"c'est fait" / "c fait" (sms)
"terminé" / "termine" (faute)
"validé" / "valide" (faute)
"ok c'est fait" / "ok c'est fait" (faute)
"ok c'est fait" / "ok c fait" (sms)
"c'est terminé" / "c'est termine" (faute)
"c'est terminé" / "c terminé" (sms)
"j'ai terminé" / "j'ai termine" (faute)
"fini" / "fini" (faute)
"c'est bon" / "c'est bon" (faute)
"c'est bon" / "c bon" (sms)
"fait" / "fait" (faute)
"terminé la tâche" / "termine la tache" (faute)
"terminé la tâche" / "terminé la tache" (sms)
"j'ai fini la tâche" / "j'ai fini la tache" (faute)
"j'ai fini la tâche" / "j'ai fini la tache" (sms)
"c'est fait la tâche" / "c'est fait la tache" (faute)
"c'est fait la tâche" / "c fait la tache" (sms)
"tâche terminée" / "tache terminee" (faute)
"tâche terminée" / "tache terminée" (sms)
"tâche finie" / "tache finie" (faute)
"tâche finie" / "tache finie" (sms)
"tâche validée" / "tache validee" (faute)
"tâche validée" / "tache validée" (sms)
"j'ai terminé la tâche" / "j'ai termine la tache" (faute)
"j'ai terminé la tâche" / "j'ai terminé la tache" (sms)
"c'est terminé la tâche" / "c'est termine la tache" (faute)
"c'est terminé la tâche" / "c terminé la tache" (sms)
"fini la tâche" / "fini la tache" (faute)
"fini la tâche" / "fini la tache" (sms)
"validé la tâche" / "valide la tache" (faute)
"validé la tâche" / "validé la tache" (sms)
"ok terminé" / "ok termine" (faute)
"c'est bon terminé" / "c'est bon termine" (faute)
"c'est bon terminé" / "c bon terminé" (sms)
"fait maintenant" / "fait maintenant" (faute)
"fait maintenant" / "fait mnt" (sms)
"terminé maintenant" / "termine maintenant" (faute)
"terminé maintenant" / "terminé mnt" (sms)
"j'ai fini maintenant" / "j'ai fini maintenant" (faute)
"j'ai fini maintenant" / "j'ai fini mnt" (sms)
"c'est fait maintenant" / "c'est fait maintenant" (faute)
"c'est fait maintenant" / "c fait mnt" (sms)
"validé maintenant" / "valide maintenant" (faute)
"validé maintenant" / "validé mnt" (sms)
"fini maintenant" / "fini maintenant" (faute)
"fini maintenant" / "fini mnt" (sms)
"c'est terminé maintenant" / "c'est termine maintenant" (faute)
"c'est terminé maintenant" / "c terminé mnt" (sms)
"j'ai terminé maintenant" / "j'ai termine maintenant" (faute)
"j'ai terminé maintenant" / "j'ai terminé mnt" (sms)
"tâche terminée maintenant" / "tache terminee maintenant" (faute)
"tâche terminée maintenant" / "tache terminée mnt" (sms)
"tâche finie maintenant" / "tache finie maintenant" (faute)
"tâche finie maintenant" / "tache finie mnt" (sms)
"tâche validée maintenant" / "tache validee maintenant" (faute)
"tâche validée maintenant" / "tache validée mnt" (sms)
"j'ai fini la tâche maintenant" / "j'ai fini la tache maintenant" (faute)
"j'ai fini la tâche maintenant" / "j'ai fini la tache mnt" (sms)
"c'est fait la tâche maintenant" / "c'est fait la tache maintenant" (faute)
"c'est fait la tâche maintenant" / "c fait la tache mnt" (sms)
"terminé la tâche maintenant" / "termine la tache maintenant" (faute)
"terminé la tâche maintenant" / "terminé la tache mnt" (sms)
"validé la tâche maintenant" / "valide la tache maintenant" (faute)
"validé la tâche maintenant" / "validé la tache mnt" (sms)
"ok c'est fait maintenant" / "ok c'est fait maintenant" (faute)
"ok c'est fait maintenant" / "ok c fait mnt" (sms)
"c'est bon terminé maintenant" / "c'est bon termine maintenant" (faute)
"c'est bon terminé maintenant" / "c bon terminé mnt" (sms)
"fait maintenant" / "fait maintenant" (faute)
"fait maintenant" / "fait mnt" (sms)
"terminé maintenant" / "termine maintenant" (faute)
"terminé maintenant" / "terminé mnt" (sms)
"j'ai fini maintenant" / "j'ai fini maintenant" (faute)
"j'ai fini maintenant" / "j'ai fini mnt" (sms)
"c'est fait maintenant" / "c'est fait maintenant" (faute)
"c'est fait maintenant" / "c fait mnt" (sms)
"validé maintenant" / "valide maintenant" (faute)
"validé maintenant" / "validé mnt" (sms)
"fini maintenant" / "fini maintenant" (faute)
"fini maintenant" / "fini mnt" (sms)
"c'est terminé maintenant" / "c'est termine maintenant" (faute)
"c'est terminé maintenant" / "c terminé mnt" (sms)
"j'ai terminé maintenant" / "j'ai termine maintenant" (faute)
"j'ai terminé maintenant" / "j'ai terminé mnt" (sms)
"tâche terminée maintenant" / "tache terminee maintenant" (faute)
"tâche terminée maintenant" / "tache terminée mnt" (sms)
"tâche finie maintenant" / "tache finie maintenant" (faute)
"tâche finie maintenant" / "tache finie mnt" (sms)
"tâche validée maintenant" / "tache validee maintenant" (faute)
"tâche validée maintenant" / "tache validée mnt" (sms)
"j'ai fini la tâche maintenant" / "j'ai fini la tache maintenant" (faute)
"j'ai fini la tâche maintenant" / "j'ai fini la tache mnt" (sms)
"c'est fait la tâche maintenant" / "c'est fait la tache maintenant" (faute)
"c'est fait la tâche maintenant" / "c fait la tache mnt" (sms)
"terminé la tâche maintenant" / "termine la tache maintenant" (faute)
"terminé la tâche maintenant" / "terminé la tache mnt" (sms)
"validé la tâche maintenant" / "valide la tache maintenant" (faute)

=

== LIST_TASKS ===
"mes tâches" / "mes taches" (faute)
"quoi faire" / "quoi faire" (normal)
"ma todo" / "ma todo" (normal)
"qu'est-ce que j'ai à faire" / "qu'est-ce que j'ai à faire" (normal)

=== HELP_REQUEST / HOW_TO ===
"comment faire" / "coment faire" (faute)
"comment je peux faire la tâche X" / "comment je peux faire la tache X" (faute)
"comment je peux faire la tâche" / "comment je peux faire la tache" (faute)
"comment faire la tâche" / "comment faire la tache" (faute)
"comment faire pour la tâche" / "comment faire pour la tache" (faute)
"c'est quoi le processus pour" / "c'est quoi le procesus pour" (faute)
"cest quoi le process pour" / "cest quoi le process pour" (normal)
"qu'est-ce que le processus pour" / "qu'est-ce que le procesus pour" (faute)
"aide-moi" / "aide-moi" (faute)
"peux-tu m'aider" / "peux-tu m'aider" (faute)
"explique-moi le processus" / "explique-moi le procesus" (faute)
"comment procéder" / "coment proceder" (faute)
"je ne sais pas comment" / "je ne sais pas coment" (faute)
"guide-moi" / "guide-moi" (faute)
"comment réaliser" / "coment realiser" (faute)
"étapes pour" / "etapes pour" (faute)
"processus pour" / "procesus pour" (faute)
"tutoriel" / "tutoriel" (faute)
"je comprends pas" / "je comprends pas" (faute)
"comment puis-je faire" / "coment puis-je faire" (faute)
"aide-moi à faire" / "aide-moi a faire" (faute)
"peux-tu m'expliquer" / "peux-tu m'expliquer" (faute)
"explique-moi comment" / "explique-moi coment" (faute)
"comment faire pour" / "coment faire pour" (faute)
"je ne comprends pas" / "je ne comprends pas" (faute)
"guide-moi pour" / "guide-moi pour" (faute)
"comment faire ça" / "coment faire ca" (faute)
"aide-moi à comprendre" / "aide-moi a comprendre" (faute)
"peux-tu me guider" / "peux-tu me guider" (faute)
"explique-moi les étapes" / "explique-moi les etapes" (faute)
"comment procéder pour" / "coment proceder pour" (faute)
"je ne sais pas" / "je ne sais pas" (faute)
"guide-moi dans" / "guide-moi dans" (faute)
"comment réaliser ça" / "coment realiser ca" (faute)
"étapes pour faire" / "etapes pour faire" (faute)
"processus pour faire" / "procesus pour faire" (faute)
"tutoriel pour" / "tutoriel pour" (faute)
"je comprends pas comment" / "je comprends pas coment" (faute)
"comment puis-je procéder" / "coment puis-je proceder" (faute)
"aide-moi à faire ça" / "aide-moi a faire ca" (faute)
"peux-tu m'aider à" / "peux-tu m'aider a" (faute)
"explique-moi comment faire" / "explique-moi coment faire" (faute)
"comment faire pour faire" / "coment faire pour faire" (faute)
"je ne comprends pas comment" / "je ne comprends pas coment" (faute)
"guide-moi pour faire" / "guide-moi pour faire" (faute)
"comment faire ça pour" / "coment faire ca pour" (faute)
"aide-moi à comprendre comment" / "aide-moi a comprendre coment" (faute)
"peux-tu me guider pour" / "peux-tu me guider pour" (faute)
"explique-moi les étapes pour" / "explique-moi les etapes pour" (faute)
"comment procéder pour faire" / "coment proceder pour faire" (faute)
"je ne sais pas comment faire" / "je ne sais pas coment faire" (faute)
"guide-moi dans la réalisation" / "guide-moi dans la realisasion" (faute)
"comment réaliser ça pour" / "coment realiser ca pour" (faute)
"étapes pour faire ça" / "etapes pour faire ca" (faute)
"processus pour faire ça" / "procesus pour faire ca" (faute)
"tutoriel pour faire" / "tutoriel pour faire" (faute)
"je comprends pas comment faire" / "je comprends pas coment faire" (faute)
"comment puis-je faire pour" / "coment puis-je faire pour" (faute)
"aide-moi à faire pour" / "aide-moi a faire pour" (faute)
"peux-tu m'aider à faire" / "peux-tu m'aider a faire" (faute)
"explique-moi comment faire pour" / "explique-moi coment faire pour" (faute)
"comment faire pour faire ça" / "coment faire pour faire ca" (faute)
"je ne comprends pas comment faire" / "je ne comprends pas coment faire" (faute)
"guide-moi pour faire ça" / "guide-moi pour faire ca" (faute)
"comment faire ça pour faire" / "coment faire ca pour faire" (faute)
"aide-moi à comprendre comment faire" / "aide-moi a comprendre coment faire" (faute)
"peux-tu me guider pour faire" / "peux-tu me guider pour faire" (faute)
"explique-moi les étapes pour faire" / "explique-moi les etapes pour faire" (faute)
"comment procéder pour faire ça" / "coment proceder pour faire ca" (faute)
"je ne sais pas comment faire ça" / "je ne sais pas coment faire ca" (faute)
"guide-moi dans la réalisation de" / "guide-moi dans la realisasion de" (faute)
"comment réaliser ça pour faire" / "coment realiser ca pour faire" (faute)
"étapes pour faire ça pour" / "etapes pour faire ca pour" (faute)
"processus pour faire ça pour" / "procesus pour faire ca pour" (faute)
"tutoriel pour faire ça" / "tutoriel pour faire ca" (faute)
"je comprends pas comment faire ça" / "je comprends pas coment faire ca" (faute)
"comment puis-je faire pour faire" / "coment puis-je faire pour faire" (faute)
"aide-moi à faire pour faire" / "aide-moi a faire pour faire" (faute)
"peux-tu m'aider à faire pour" / "peux-tu m'aider a faire pour" (faute)
"explique-moi comment faire pour faire" / "explique-moi coment faire pour faire" (faute)
"comment faire pour faire ça pour" / "coment faire pour faire ca pour" (faute)
"je ne comprends pas comment faire ça" / "je ne comprends pas coment faire ca" (faute)
"guide-moi pour faire ça pour" / "guide-moi pour faire ca pour" (faute)
"comment faire ça pour faire pour" / "coment faire ca pour faire pour" (faute)
"aide-moi à comprendre comment faire pour" / "aide-moi a comprendre coment faire pour" (faute)
"peux-tu me guider pour faire pour" / "peux-tu me guider pour faire pour" (faute)
"explique-moi les étapes pour faire pour" / "explique-moi les etapes pour faire pour" (faute)
"comment procéder pour faire ça pour" / "coment proceder pour faire ca pour" (faute)
"je ne sais pas comment faire ça pour" / "je ne sais pas coment faire ca pour" (faute)
"guide-moi dans la réalisation de ça" / "guide-moi dans la realisasion de ca" (faute)
"comment réaliser ça pour faire pour" / "coment realiser ca pour faire pour" (faute)
"étapes pour faire ça pour faire" / "etapes pour faire ca pour faire" (faute)
"processus pour faire ça pour faire" / "procesus pour faire ca pour faire" (faute)
"tutoriel pour faire ça pour" / "tutoriel pour faire ca pour" (faute)
"je comprends pas comment faire ça pour" / "je comprends pas coment faire ca pour" (faute)
"comment puis-je faire pour faire pour" / "coment puis-je faire pour faire pour" (faute)
"aide-moi à faire pour faire pour" / "aide-moi a faire pour faire pour" (faute)
"peux-tu m'aider à faire pour faire" / "peux-tu m'aider a faire pour faire" (faute)
"explique-moi comment faire pour faire pour" / "explique-moi coment faire pour faire pour" (faute)
"comment faire pour faire ça pour faire" / "coment faire pour faire ca pour faire" (faute)
"je ne comprends pas comment faire ça pour" / "je ne comprends pas coment faire ca pour" (faute)
"guide-moi pour faire ça pour faire" / "guide-moi pour faire ca pour faire" (faute)
"comment faire ça pour faire pour faire" / "coment faire ca pour faire pour faire" (faute)
"aide-moi à comprendre comment faire pour faire" / "aide-moi a comprendre coment faire pour faire" (faute)
"peux-tu me guider pour faire pour faire" / "peux-tu me guider pour faire pour faire" (faute)
"explique-moi les étapes pour faire pour faire" / "explique-moi les etapes pour faire pour faire" (faute)
"comment procéder pour faire ça pour faire" / "coment proceder pour faire ca pour faire" (faute)

**Extraction d'ENTITÉS** :
- Tasks : Noms de tâches mentionnées (même avec fautes)
- Dates : "demain", "dem1n", "lundi", "dans 2 jours", "14h"
- Projects : Noms de projets
- Habits : Noms d'habitudes
- Numbers : Nombres (durée, quantité, etc.)

**Contexte ÉMOTIONNEL** :
- positive : Enthousiaste, motivé, content
- neutral : Normal, factuel
- negative : Triste, découragé
- stressed : Stressé, sous pression, urgent
- motivated : Déterminé, énergique

**RÈGLES IMPORTANTES** :
1. Ignore les fautes d'orthographe courantes
2. Comprends les abréviations SMS
3. Sois flexible sur la formulation
4. Si plusieurs intentions possibles, choisis la plus probable
5. Si vraiment incertain, utilise "conversation" avec category "unclear"

Réponds UNIQUEMENT en JSON valide.`;

    const userPrompt = `Message utilisateur original : "${message}"
Message normalisé : "${normalizedMessage}"

${userContext ? `
Contexte utilisateur :
- Tâches en cours : ${userContext.pendingTasks || 0}
- Habitudes du jour : ${userContext.todayHabits || 0}
- Session Deep Work active : ${userContext.hasActiveSession ? 'Oui' : 'Non'}
` : ''}

Analyse ce message et réponds au format JSON :
{
  "type": "action|question|conversation",
  "category": "create_task|advice_request|greeting|etc",
  "confidence": 0.95,
  "entities": {
    "tasks": ["tâche 1"],
    "dates": ["demain"],
    "projects": [],
    "habits": [],
    "numbers": [2]
  },
  "parameters": {
    "urgency": "high|medium|low",
    "duration": minutes,
    "any_other_param": "value"
  },
  "emotionalContext": "positive|neutral|negative|stressed|motivated",
  "requiresAction": true|false,
  "suggestedResponse": "Réponse suggérée si pas d'action"
}`;

    try {
      const response = await openai.chat.completions.create({
        model: 'gpt-4-turbo-preview',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.2,
        response_format: { type: 'json_object' }
      });

      const content = response.choices[0].message.content;
      if (!content) {
        throw new Error('Pas de réponse de l\'IA');
      }

      const intent = JSON.parse(content) as Intent;

      // Normaliser la confiance
      intent.confidence = Math.max(0, Math.min(1, intent.confidence));

      return intent;

    } catch (error) {
      console.error('Erreur détection intention:', error);
      
      // Fallback : intention neutre avec réponse par défaut
      return {
        type: 'conversation',
        category: 'unclear',
        confidence: 0.3,
        entities: {},
        parameters: {},
        emotionalContext: 'neutral',
        requiresAction: false,
        suggestedResponse: "Je n'ai pas bien compris. Peux-tu reformuler ?"
      };
    }
  }

  /**
   * Générer une réponse conversationnelle intelligente
   */
  static async generateConversationalResponse(
    message: string,
    intent: Intent,
    userContext?: any
  ): Promise<string> {
    const systemPrompt = `Tu es l'assistant IA personnel de productivité Productif.io.

Ton rôle : Aider l'utilisateur à être plus productif de manière bienveillante et motivante.

Ton style :
- Amical et encourageant
- Concis (2-3 phrases max pour conversation simple)
- Utilise des emojis pertinents
- Donne des conseils actionnables
- Personnalise selon le contexte

Tu PEUX :
- Donner des conseils de productivité
- Expliquer les fonctionnalités de Productif.io
- Motiver et encourager
- Proposer des stratégies
- Répondre aux questions sur la gestion du temps
- Suggérer des actions concrètes

Tu NE PEUX PAS :
- Donner des conseils médicaux
- Discuter de sujets non liés à la productivité
- Faire des promesses impossibles

${userContext ? `
Contexte utilisateur :
- ${userContext.pendingTasks || 0} tâche(s) en attente
- ${userContext.completedToday || 0} tâche(s) complétée(s) aujourd'hui
- Niveau d'énergie estimé : ${userContext.energyLevel || 'moyen'}
- Session active : ${userContext.hasActiveSession ? 'Oui (Deep Work)' : 'Non'}
` : ''}`;

    const userPrompt = `Message utilisateur : "${message}"

Intention détectée : ${intent.category}
Contexte émotionnel : ${intent.emotionalContext}

Génère une réponse naturelle, utile et personnalisée.`;

    try {
      const response = await openai.chat.completions.create({
        model: 'gpt-4-turbo-preview',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.7,
        max_tokens: 300
      });

      return response.choices[0].message.content || "Je suis là pour t'aider ! Comment puis-je t'assister ?";

    } catch (error) {
      console.error('Erreur génération réponse:', error);
      return "Je suis là pour t'aider ! Que puis-je faire pour toi ? 🚀";
    }
  }
}

