/**
 * Dictionnaire exhaustif de variations et synonymes pour chaque commande
 * Permet de comprendre les requêtes même avec des formulations différentes
 */

export interface CommandVariation {
  primaryKeywords: string[]
  contextKeywords: string[]
  variations: string[]
  minConfidence: number
}

export const COMMAND_VARIATIONS: Record<string, CommandVariation> = {
  start_deepwork: {
    primaryKeywords: ['commence', 'démarre', 'start', 'lance', 'go', 'début', 'débuter', 'démarrer'],
    contextKeywords: ['travailler', 'travail', 'deep work', 'deepwork', 'focus', 'concentration', 'session', 'bosser', 'boulot'],
    variations: [
      // Formulations normales
      'je commence à travailler',
      'je démarre une session',
      'lance une session de travail',
      'go deep work',
      'je veux travailler',
      'je vais bosser',
      'commence le travail',
      'démarre le deep work',
      'start deep work',
      'je commence le travail',
      'je démarre le travail',
      'lance une session',
      'je veux faire du deep work',
      'je vais faire une session',
      'commence une session de travail',
      'démarre une session de deep work',
      'je commence une session',
      'je démarre une session de travail',
      'on commence à travailler',
      'on démarre une session',
      'c\'est parti pour travailler',
      'c\'est parti pour le travail',
      'allez on y va',
      'allez on commence',
      'allez on démarre',
      'on y va',
      'c\'est parti',
      'je veux me concentrer',
      'je veux faire du focus',
      'je veux me mettre au travail',
      'je veux me mettre au boulot',
      'je veux me concentrer sur mon travail',
      'je veux faire une session de concentration',
      'je veux faire une session de focus',
      'je veux faire une session de deep work',
      'je veux faire une session de travail',
      'je veux faire une session',
      'je veux commencer à travailler',
      'je veux démarrer une session',
      'je veux lancer une session',
      'je veux commencer une session',
      'je veux démarrer le travail',
      'je veux commencer le travail',
      'je veux lancer le travail',
      'je veux commencer',
      'je veux démarrer',
      'je veux lancer',
      'je veux commencer à bosser',
      'je veux démarrer à bosser',
      'je veux lancer à bosser',
      'je peux commencer à travailler ?',
      'je peux démarrer une session ?',
      'je peux lancer une session ?',
      'je peux commencer ?',
      'je peux démarrer ?',
      'je peux lancer ?',
      'est-ce que je peux commencer ?',
      'est-ce que je peux démarrer ?',
      'est-ce que je peux lancer ?',
      'commence',
      'démarre',
      'lance',
      'go',
      'start',
      'commence à travailler',
      'démarre une session',
      'lance une session',
      'commence le travail',
      'démarre le travail',
      'lance le travail',
      'commence une session',
      'démarre une session',
      'lance une session',
      'je commence à travailler pour 25 minutes',
      'je démarre une session de 25 minutes',
      'lance une session de 25 minutes',
      'je veux travailler 25 minutes',
      'je vais bosser 25 minutes',
      'commence le travail pour 25 minutes',
      'démarre le deep work pour 25 minutes',
      'start deep work for 25 minutes',
      'je commence le travail pour 25 minutes',
      'je démarre le travail pour 25 minutes',
      'lance une session pour 25 minutes',
      'je veux faire du deep work 25 minutes',
      'je vais faire une session de 25 minutes',
      'commence une session de travail de 25 minutes',
      'démarre une session de deep work de 25 minutes',
      // Avec fautes d'orthographe
      'je comence à travaiiler',
      'je démarre une session',
      'kommence le travail',
      'commance à travailler',
      'démare une session',
      'je veux travaiiler',
      'je comence',
      'je démarre',
      'kommence',
      'commance',
      'démare',
      'je veux travaiiler',
      // SMS/Informel
      'c parti pour bosser',
      'go bosser',
      'c\'est parti',
      'j\'veux bosser',
      'j\'vais bosser',
      'on y va',
      'allez',
      'c parti',
      'go',
      'j\'veux',
      'j\'vais',
    ],
    minConfidence: 0.7
  },

  end_deepwork: {
    primaryKeywords: ['termine', 'fini', 'stop', 'arrête', 'arrêter', 'terminer', 'finir'],
    contextKeywords: ['session', 'deep work', 'deepwork', 'travail', 'travail', 'travail'],
    variations: [
      'je termine la session',
      'je finis la session',
      'stop la session',
      'arrête la session',
      'termine le travail',
      'fini le travail',
      'stop le travail',
      'arrête le travail',
      'je termine',
      'je finis',
      'stop',
      'arrête',
      'c\'est terminé',
      'c\'est fini',
      'c\'est fait',
      'terminé',
      'fini',
      'fait',
      'ok c\'est fait',
      'ok c\'est terminé',
      'ok c\'est fini',
      'c\'est bon',
      'c\'est ok',
      'terminer la session',
      'finir la session',
      'arrêter la session',
      'terminer le travail',
      'finir le travail',
      'arrêter le travail',
      'je veux terminer',
      'je veux finir',
      'je veux arrêter',
      'je peux terminer ?',
      'je peux finir ?',
      'je peux arrêter ?',
      'est-ce que je peux terminer ?',
      'est-ce que je peux finir ?',
      'est-ce que je peux arrêter ?',
      // SMS/Informel
      'c terminé',
      'c fini',
      'c fait',
      'ok c fait',
      'ok c terminé',
      'ok c fini',
      'c bon',
      'c ok',
      'terminé',
      'fini',
      'fait',
    ],
    minConfidence: 0.7
  },

  pause_deepwork: {
    primaryKeywords: ['pause', 'pauser', 'mettre en pause'],
    contextKeywords: ['session', 'deep work', 'deepwork', 'travail'],
    variations: [
      'pause la session',
      'mets en pause',
      'mettre en pause',
      'je veux faire une pause',
      'je veux me mettre en pause',
      'je veux pauser',
      'je peux faire une pause ?',
      'est-ce que je peux faire une pause ?',
      'pause',
      'pauser',
      'mettre en pause la session',
      'mettre en pause le travail',
      'mettre en pause le deep work',
      'je veux mettre en pause',
      'je veux pauser la session',
      'je veux pauser le travail',
      'je veux pauser le deep work',
      // SMS/Informel
      'pause',
      'pauser',
      'c pause',
      'je pause',
    ],
    minConfidence: 0.7
  },

  resume_deepwork: {
    primaryKeywords: ['reprend', 'continue', 'reprise', 'reprendre', 'continuer'],
    contextKeywords: ['session', 'deep work', 'deepwork', 'travail'],
    variations: [
      'reprend la session',
      'continue la session',
      'reprendre la session',
      'continuer la session',
      'je reprends',
      'je continue',
      'reprend',
      'continue',
      'reprendre',
      'continuer',
      'je veux reprendre',
      'je veux continuer',
      'je peux reprendre ?',
      'je peux continuer ?',
      'est-ce que je peux reprendre ?',
      'est-ce que je peux continuer ?',
      'reprendre le travail',
      'continuer le travail',
      'reprendre le deep work',
      'continuer le deep work',
      'je veux reprendre le travail',
      'je veux continuer le travail',
      'je veux reprendre le deep work',
      'je veux continuer le deep work',
      // SMS/Informel
      'reprend',
      'continue',
      'c reprend',
      'c continue',
      'je reprend',
      'je continue',
    ],
    minConfidence: 0.7
  },

  status_deepwork: {
    primaryKeywords: ['statut', 'status', 'état', 'en cours', 'active', 'actif'],
    contextKeywords: ['session', 'deep work', 'deepwork', 'travail'],
    variations: [
      'statut de la session',
      'statut du travail',
      'statut du deep work',
      'état de la session',
      'état du travail',
      'état du deep work',
      'session en cours',
      'travail en cours',
      'deep work en cours',
      'session active',
      'travail actif',
      'deep work actif',
      'quelle est la session ?',
      'quelle est le travail ?',
      'quelle est le deep work ?',
      'où en est la session ?',
      'où en est le travail ?',
      'où en est le deep work ?',
      'combien de temps reste ?',
      'combien de temps il reste ?',
      'combien de temps reste-t-il ?',
      'il reste combien de temps ?',
      'temps restant',
      'temps écoulé',
      'progression',
      'avancement',
      'je veux savoir où j\'en suis',
      'je veux savoir le statut',
      'je veux savoir l\'état',
      'je veux savoir la progression',
      'je veux savoir l\'avancement',
      // SMS/Informel
      'statut',
      'status',
      'état',
      'où j\'en suis',
      'où j\'en suis ?',
      'combien il reste',
      'combien il reste ?',
      'temps restant',
      'temps écoulé',
    ],
    minConfidence: 0.7
  },

  plan_tomorrow: {
    primaryKeywords: ['planifie', 'planifier', 'organise', 'organiser', 'prépare', 'préparer', 'planning'],
    contextKeywords: ['demain', 'demain', 'demain', 'journée', 'journee', 'tâches', 'taches', 'todo'],
    variations: [
      'planifie demain',
      'planifier demain',
      'organise ma journée de demain',
      'organiser ma journée de demain',
      'prépare demain',
      'préparer demain',
      'mes tâches de demain',
      'mes taches de demain',
      'ce que j\'ai à faire demain',
      'ma to-do demain',
      'planning demain',
      'organise demain',
      'préparer demain',
      'planifier demain',
      'organiser demain',
      'je veux planifier demain',
      'je veux organiser demain',
      'je veux préparer demain',
      'aide-moi à organiser demain',
      'aide-moi à planifier demain',
      'aide-moi à préparer demain',
      'qu\'est-ce que je dois faire demain',
      'qu\'est-ce que j\'ai à faire demain',
      'que dois-je faire demain',
      'que j\'ai à faire demain',
      'mes tâches pour demain',
      'mes taches pour demain',
      'ma liste pour demain',
      'mon planning pour demain',
      'mon organisation pour demain',
      'préparer ma journée de demain',
      'organiser ma journée de demain',
      'planifier ma journée de demain',
      'je veux préparer ma journée de demain',
      'je veux organiser ma journée de demain',
      'je veux planifier ma journée de demain',
      // SMS/Informel
      'planif demain',
      'organise dem1n',
      'prépare dem1n',
      'planif dem1n',
      'organise dem1n',
      'prépare dem1n',
      'mes taches dem1n',
      'mes tâches dem1n',
      'ma todo dem1n',
      'ma to-do dem1n',
      'planning dem1n',
      'organise dem1n',
      'prépare dem1n',
    ],
    minConfidence: 0.7
  },

  journal: {
    primaryKeywords: ['journal', 'note', 'raconter', 'raconte', 'récap', 'recap', 'résumé', 'resume'],
    contextKeywords: ['journée', 'journee', 'ma journée', 'ma journee', 'sa journée', 'sa journee'],
    variations: [
      'journal',
      'note de ma journée',
      'raconter ma journée',
      'récap de ma journée',
      'note de journée',
      'journal de la journée',
      'note ma journée',
      'raconte ma journée',
      'résumé de ma journée',
      'note de sa journée',
      'journal de sa journée',
      'note journee',
      'note de journee',
      'raconter journee',
      'note de ma journee',
      'raconter ma journee',
      'récap de ma journee',
      'recap de ma journee',
      'résumé de ma journee',
      'resume de ma journee',
      'note de sa journee',
      'journal de sa journee',
      'je veux noter ma journée',
      'je veux raconter ma journée',
      'je veux faire un journal',
      'je veux faire une note',
      'je veux faire un récap',
      'je veux faire un résumé',
      'je peux noter ma journée ?',
      'je peux raconter ma journée ?',
      'je peux faire un journal ?',
      'je peux faire une note ?',
      'je peux faire un récap ?',
      'je peux faire un résumé ?',
      'est-ce que je peux noter ma journée ?',
      'est-ce que je peux raconter ma journée ?',
      'est-ce que je peux faire un journal ?',
      'est-ce que je peux faire une note ?',
      'est-ce que je peux faire un récap ?',
      'est-ce que je peux faire un résumé ?',
      // SMS/Informel
      'journal',
      'note',
      'raconter',
      'raconte',
      'récap',
      'recap',
      'résumé',
      'resume',
      'note journee',
      'note de journee',
      'raconter journee',
      'note de ma journee',
      'raconter ma journee',
      'récap de ma journee',
      'recap de ma journee',
      'résumé de ma journee',
      'resume de ma journee',
    ],
    minConfidence: 0.7
  },

  complete_task: {
    primaryKeywords: ['fini', 'terminé', 'terminé', 'validé', 'validé', 'complété', 'complété', 'fait', 'check'],
    contextKeywords: ['tâche', 'tache', 'todo', 'to-do'],
    variations: [
      'j\'ai fini',
      'c\'est fait',
      'terminé',
      'fini',
      'validé',
      'check',
      'fait',
      'complété',
      'terminée',
      'finie',
      'validée',
      'complétée',
      'j\'ai terminé',
      'j\'ai fini la tâche',
      'c\'est terminé',
      'c\'est fini',
      'c\'est validé',
      'j\'ai complété',
      'j\'ai validé',
      'terminer',
      'finir',
      'valider',
      'compléter',
      'j\'ai fait',
      'c\'est bon',
      'c\'est ok',
      'ok c\'est fait',
      'ok c\'est terminé',
      'ok c\'est fini',
      'ok c\'est validé',
      'ok c\'est complété',
      'je veux terminer',
      'je veux finir',
      'je veux valider',
      'je veux compléter',
      'je peux terminer ?',
      'je peux finir ?',
      'je peux valider ?',
      'je peux compléter ?',
      'est-ce que je peux terminer ?',
      'est-ce que je peux finir ?',
      'est-ce que je peux valider ?',
      'est-ce que je peux compléter ?',
      // SMS/Informel
      'c fait',
      'c terminé',
      'c fini',
      'c validé',
      'c complété',
      'ok c fait',
      'ok c terminé',
      'ok c fini',
      'ok c validé',
      'ok c complété',
      'c bon',
      'c ok',
      'terminé',
      'fini',
      'validé',
      'complété',
      'fait',
      'check',
    ],
    minConfidence: 0.7
  },

  list_tasks: {
    primaryKeywords: ['liste', 'lister', 'affiche', 'afficher', 'montre', 'montrer', 'voir', 'voir'],
    contextKeywords: ['tâches', 'taches', 'todo', 'to-do', 'aujourd\'hui', 'aujourdhui', 'demain', 'demain'],
    variations: [
      'mes tâches',
      'mes taches',
      'ma liste',
      'ma todo',
      'ma to-do',
      'liste des tâches',
      'liste des taches',
      'affiche mes tâches',
      'afficher mes tâches',
      'montre mes tâches',
      'montrer mes tâches',
      'voir mes tâches',
      'voir mes taches',
      'qu\'est-ce que j\'ai à faire',
      'que j\'ai à faire',
      'quoi faire',
      'que faire',
      'mes tâches aujourd\'hui',
      'mes taches aujourdhui',
      'mes tâches de demain',
      'mes taches de demain',
      'je veux voir mes tâches',
      'je veux voir mes taches',
      'je veux voir ma liste',
      'je veux voir ma todo',
      'je veux voir ma to-do',
      'je peux voir mes tâches ?',
      'je peux voir mes taches ?',
      'je peux voir ma liste ?',
      'je peux voir ma todo ?',
      'je peux voir ma to-do ?',
      'est-ce que je peux voir mes tâches ?',
      'est-ce que je peux voir mes taches ?',
      'est-ce que je peux voir ma liste ?',
      'est-ce que je peux voir ma todo ?',
      'est-ce que je peux voir ma to-do ?',
      // SMS/Informel
      'mes taches',
      'ma liste',
      'ma todo',
      'ma to-do',
      'liste',
      'taches',
      'tâches',
      'todo',
      'to-do',
      'quoi faire',
      'que faire',
      'mes taches aujourdhui',
      'mes taches dem1n',
      'mes tâches dem1n',
    ],
    minConfidence: 0.7
  },
}

